### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ashish1099** [zrepl/zrepl#901]
Hello,

There has quite a commits that got merged, and the last release was back in 2023, can we please cut a release now

**Comment by problame** [comment]
Done :) https://github.com/zrepl/zrepl/releases/tag/v0.7.0

**Comment by riyad** [comment]
Thanks for the release, but it seems the APT repo didn't get the update. On Ubuntu 24.04 (noble) and 25.10 (questing) I still get 0.6.1-2 as the latest version.

**Comment by problame** [comment]
Yes, going to update the repos soon. I wait a couple of days in case there’s feedback from the very eager users who consume the GH release directly
